safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: yandex2
default_width: 1024
default_ratio: 16x9     # 4x3, 16x9, 16x10
default_lang: ru
default_body_class: list

presentation:
    title: Как мы работаем над скоростью Поиска
    service: Поиск
    nda: false
    lang: ru            # ru, en

author:
    name: Андрей Прокопюк
    position: Разработчик скорости
    company:
        name: Яндекс
        url:  http://yandex.ru/

# второй автор
# author2:
#   name: Автор
#   position: Должность

fork_url: https://github.com/andre487/saturday-2017-11-velocity
progress: true # отображение прогресс-бара в нижней части слайдов
